name: seekode
repository: https://github.com/seekode/seekode
description: The official app of seekode.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_svg: ^2.0.5
  url_launcher: ^6.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.1
  freezed: ^2.3.2


flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/flags/fr.svg
    - assets/images/flags/en.svg
    - assets/images/logo.svg
    - assets/images/networks/instagram.svg
    - assets/images/networks/tiktok.svg
    - assets/images/networks/phone.svg
    - assets/images/networks/mail.svg
    - assets/images/networks/mail.svg
    - assets/images/header.png
    - assets/images/freelance.png
    - assets/images/training.png
    - assets/images/services.png
    - assets/images/services/responsive.png
    - assets/images/services/design.png
    - assets/images/services/coding.png
    - assets/images/services/tips.png
    - assets/images/services/support.png
    - assets/images/services/handshake.png
    - assets/images/trainings/seekorp.svg
    - assets/images/trainings/youtube.svg
    - assets/images/trainings/discord.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpaceAge
      fonts:
        - asset: assets/fonts/space_age.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
