name: seekode
repository: https://github.com/seekode/seekode
description: The official app of seekode.
publish_to: 'none'
version: 1.5.5+3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.3
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9


flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/flags/fr.svg
    - assets/images/flags/en.svg
    - assets/images/logo.svg
    - assets/images/logo-text.svg
    - assets/images/networks/instagram.svg
    - assets/images/networks/tiktok.svg
    - assets/images/networks/linkedin.svg
    - assets/images/networks/tiktok.svg
    - assets/images/networks/phone.svg
    - assets/images/networks/mail.svg
    - assets/images/networks/playstore.svg
    - assets/images/networks/windows.svg
    - assets/images/networks/qrcode.png
    - assets/images/networks/phone.png
    - assets/images/header.png
    - assets/images/freelance.png
    - assets/images/training.png
    - assets/images/services.png
    - assets/images/services/responsive.png
    - assets/images/services/design.png
    - assets/images/services/coding.png
    - assets/images/services/tips.png
    - assets/images/services/support.png
    - assets/images/services/handshake.png
    - assets/images/trainings/seekorp.svg
    - assets/images/trainings/udemy.svg
    - assets/images/trainings/youtube.svg
    - assets/images/trainings/discord.svg
    - assets/images/projects/seekode.png
    - assets/images/projects/formawave.png
    - assets/images/projects/capters.png
    - assets/images/projects/ec-controlling.png
    - assets/images/projects/tennisvexin-thelle.png
    - assets/images/projects/desmarez.png
    - assets/images/projects/sophrologue.png
    - assets/images/about/seekode.jpg
    - assets/images/about/microsoft_teams.svg
    - assets/images/about/responsive.svg
    - assets/images/about/html.svg
    - assets/images/about/figma.svg
    - assets/images/about/trello.svg
    - assets/images/about/git.svg
    - assets/images/about/github.svg
    - assets/images/about/sass.svg
    - assets/images/about/css.svg
    - assets/images/about/filezilla.svg
    - assets/images/about/react-native.svg
    - assets/images/about/react.svg
    - assets/images/about/javascript.svg
    - assets/images/about/vscode.svg
    - assets/images/about/android_studio.svg
    - assets/images/about/wordpress.svg
    - assets/images/about/nodejs.svg
    - assets/images/about/php.svg
    - assets/images/about/dart.svg
    - assets/images/about/mongodb.svg
    - assets/images/about/firebase.svg
    - assets/images/about/mysql.svg
    - assets/images/about/flutter.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SpaceAge
      fonts:
        - asset: assets/fonts/space_age.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages